# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    "name": "PayrollX",
    "version": "17.0.1.1.0",
    "category": "Payroll",
    "website": "https://www.superxtech.io",
    
    "summary": "Manage your employee payroll records",
    "license": "LGPL-3",
    "author": "SuperXTech",
    "depends": [
        "hr_contract",
        "hr_holidays",
        "mail",
    ],
    "data": [
        "security/hr_payroll_security.xml",
        "security/ir.model.access.csv",
        "data/hr_payroll_sequence.xml",
        "data/hr_payroll_data.xml",
        "wizard/hr_payroll_contribution_register_report_views.xml",
        "wizard/hr_payroll_payslips_by_employees_views.xml",
        "views/menus.xml",
        "views/hr_contract_views.xml",
        "views/hr_payroll_structure_views.xml",
        "views/salary_structure_type_views.xml",
        "views/unpaid_work_entry_type_views.xml",
        "views/hr_salary_rule_category_views.xml",
        "views/hr_contribution_register_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_payslip_line_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/hr_employee_views.xml",
        "views/report_contributionregister.xml",
        "views/report_payslip.xml",
        "views/report_payslipdetails.xml",
        "report/report.xml",
        "views/res_config_settings_views.xml",
        "wizard/hr_payroll_send_email.xml",
        "wizard/hr_payslip_change_state_view.xml",
        "views/hr_leave_type.xml",
         'views/salary_attachment_views.xml',
                    # 'views/contract_views.xml',
'views/work_entry_timeoff_views.xml',
'views/work_entry_views.xml',
        'views/payroll_reporting_views.xml',
     'views/other_input_type_views.xml',
     'views/working_schedule_views.xml',

    ],
    "demo": ["demo/hr_payroll_demo.xml"],
    "application": True,
    "maintainers": ["appstogrow", "nimarosa"],
}
